services:
  docs:
    image: my_event_manager_local_docs
    container_name: my_event_manager_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./my_event_manager:/app/my_event_manager:z
    ports:
      - '9000:9000'
    command: /start-docs
